name: museopheno
dependencies:
        - python=3.7
        - GDAL
        - pip:
           - nbsphinx
           - sphinx-rtd-theme
           - sphinx-gallery
           - joblib
           - museotoolbox

