# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
    image: latest
    
python:
    version: 3.7
    system_packages: true
    install:
      - requirements: requirements-dev.txt
      - method: setuptools
        path: .
     
conda:
    environment: .environment.yml
