language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.6
  - os: linux
    sudo: required
    python: 3.7
install:
- pip install -r requirements.txt
- pip install .
script:
- python setup.py develop

deploy:
  provider: pypi
  user: __token__
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJGU2Y2QwMGFjLTgzZTktNDc0MS1hYWYxLTY2ZWI4ZmY2NWM5ZQACO3sicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJtdXNlb3BoZW5vIl19LCAidmVyc2lvbiI6IDF9AAAGIJtXHl5gQ_BgZPEGR0qMSfv-D5ihpyxvILNBss_7e21Y
  on:
    tags: true
    branch: master
  skip_existing: true
