language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.6
  - os: linux
    sudo: required
    python: 3.7
install:
- pip install -r requirements.txt
- pip install .
script:
- python setup.py develop

deploy:
  provider: pypi
  user: "karasiak"
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJDVhOWQ0ZTM1LTY5NDMtNDU4ZC05MmM0LThlODMxMWRiZDNkMgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgAbf4SyDR8kRdHdmMCCNNeYOXlB2OFaxmmUi0fS-eka8
  on:
    tags: true
    branch: master
  skip_existing: true
